(module
  (import "ic0" "msg_arg_data_copy" (func $args (param i32 i32 i32)))
  (import "ic0" "msg_reply_data_append" (func $append (param i32 i32)))
  (import "ic0" "msg_reply" (func $reply))
  (import "ic0" "stable64_size" (func $size (result i64)))
  (import "ic0" "stable64_grow" (func $grow (param i64) (result i64)))
  (import "ic0" "stable64_write" (func $write (param i64 i64 i64)))
  (import "ic0" "stable64_read" (func $read (param i64 i64 i64)))
  (import "ic0" "certified_data_set" (func $certify (param i32 i32)))
  (memory (export "memory") 2)
  (global $counter (export "counter") (mut i64) (i64.const 0))
  (func (export "canister_update write")
    (call $args (i32.const 0) (i32.const 0) (i32.const 8))
    (global.set $counter (i64.load (i32.const 0)))
    (if (i64.eqz (call $size))
      (then (drop (call $grow (i64.const 1)))))
    (call $write (i64.const 0) (i64.const 0) (i64.const 8))
    (call $certify (i32.const 0) (i32.const 8))
    (call $reply))
  (func (export "canister_query read")
    (i64.store (i32.const 8) (global.get $counter))
    (call $read (i64.const 16) (i64.const 0) (i64.const 8))
    (call $append (i32.const 0) (i32.const 24))
    (call $reply)))
