[workspace]
members = ["crates/ic-backup", "crates/ic-backup-agent"]
resolver = "3"

[workspace.package]
version = "0.11.3"
edition = "2024"
rust-version = "1.88.0"
license = "MIT"
repository = "https://github.com/dragginzgame/ic-backup"
publish = ["crates-io"]

[workspace.dependencies]
candid = "0.10"
command-fds = "=0.3.3"
ic-agent = { version = "0.49.2", default-features = false }
ic-backup = { version = "0.11.3", path = "crates/ic-backup" }
ic-host-artifacts = { version = "0.9", default-features = false }
ic-host-fs = { version = "0.9", default-features = false }
ic-management-canister-types = "=0.11.0"
ic-metrics = { version = "0.3", default-features = false }
ic-testkit = "0.27"
ic_principal = { version = "=0.1.5", default-features = false, features = [
    "convert",
] }
rustix = { version = "1.1.4", features = ["fs"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sha2 = "0.10.9"
thiserror = "2.0"
tokio = { version = "1.50", features = ["rt-multi-thread", "macros"] }
wat = "1.227"

[workspace.lints.rust]
unsafe_code = "forbid"
missing_docs = "deny"
dead_code = "deny"
unfulfilled_lint_expectations = "deny"

[workspace.lints.clippy]
all = { level = "warn", priority = -1 }
pedantic = { level = "warn", priority = -1 }
