[workspace]
members = ["crates/ic-backup"]
resolver = "3"

[workspace.package]
version = "0.4.2"
edition = "2024"
rust-version = "1.91.0"
license = "MIT"
repository = "https://github.com/dragginzgame/ic-backup"
publish = ["crates-io"]

[workspace.dependencies]
candid = "0.10"
command-fds = "=0.3.3"
ic-host-artifacts = { version = "0.3.0", default-features = false }
ic-host-fs = { version = "0.3.0", default-features = false }
ic-management-canister-types = "=0.11.0"
ic-metrics = { version = "0.2", default-features = false }
ic_principal = { version = "=0.1.5", default-features = false, features = [
    "convert",
] }
rustix = { version = "1.1.4", features = ["fs"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sha2 = "0.10.9"
thiserror = "2.0"

[workspace.lints.rust]
unsafe_code = "forbid"
missing_docs = "deny"
dead_code = "deny"
unfulfilled_lint_expectations = "deny"

[workspace.lints.clippy]
all = { level = "warn", priority = -1 }
pedantic = { level = "warn", priority = -1 }
